using System;

static class AppChangelog
{
    // User-visible features and fixes since the first C# version.
    public static readonly string Text = String.Join("\r\n", new[]
    {
        "2.5.0 — 30/09/2026", "",
        "• RAM extraction can be selected when physical memory is sufficient; missing RAM drive guidance is clearer.",
        "• Missing codecs are explained before conversion starts.",
        "• PS1 covers can fall back to Libretro thumbnails.",
        "• Compatibility with older devices saves CHD version 4 with zlib.", "",
        "2.4.0 — 30/09/2026", "",
        "• Archives are extracted with SharpCompress without the 7-Zip application or DLL.",
        "• Optional extraction to an existing RAM disk, with memory and capacity checks.",
        "• RAM extraction requires more than 12 GiB total and at least 5 GiB available; CHD output stays on disk.", "",
        "2.3.0 — 29/09/2026", "",
        "• Multi-file BIN discs without CUE can be reconstructed when their track layout is identifiable.",
        "• Fixed false link detection in the former 7-Zip RAR fallback.",
        "• Automatic system detection distinguishes PS1 and PS2; selected-platform filtering remains available.",
        "• English and Brazilian Portuguese interface, clearer encoding help and a reset button.",
        "• Crash logs and a report issue action are available.", "",
        "2.2.0 — 26/09/2026", "",
        "• CPU and disk readings now reflect the application and converters it starts.",
        "• Multi-track PS2 CDs can be converted when their layout can be identified.",
        "• Different game revisions are kept as separate outputs.",
        "• Stop Now cancels the current task and cleans its temporary files.",
        "• The last input folder is remembered; output defaults to its otimizados folder.",
        "• Codecs are chosen with labeled checkboxes, and tool paths have a Settings page.",
        "• PS1 cover art is now supported.", "",
        "2.1.0 — 26/09/2026", "",
        "• Modern interface with cards, collapsible encoding options and help tooltips.",
        "• DiscForge CHD identity, icon and build date appear in the app.",
        "• The game panel adapts to narrow windows.", "",
        "2.0.0 — 25/09/2026", "",
        "• WinUI 3 interface with game details and covers in WebView2.",
        "• SharpCompress extraction with 7-Zip fallback for incompatible archives.",
        "• Portable distribution with the components needed to run.", "",
        "1.3.0 — 21/09/2026", "",
        "• Covers load during identification, with retries after temporary failures.",
        "• Current input timer and live CPU and disk metrics.",
        "• Thread count is filled from the local machine.", "",
        "1.2.0 — 20/09/2026", "",
        "• PS1/PS2 images and archives convert to CHD.",
        "• Folder, platform, codec, hunk and thread settings.",
        "• Serial lookup, game names and PS2 covers.",
        "• Resume skips games already converted; CHDs are verified before optional archive removal."
    });

    public static readonly string PortugueseText = String.Join("\r\n", new[]
    {
        "2.5.0 — 30/09/2026", "",
        "• A extração em RAM pode ser marcada com memória suficiente; orientação da unidade RAM mais clara.",
        "• Codecs ausentes são explicados antes da conversão.",
        "• Capas de PS1 podem usar miniaturas Libretro como reserva.",
        "• Compatibilidade com dispositivos antigos salva CHD versão 4 com zlib.", "",
        "2.4.0 — 30/09/2026", "",
        "• Extração com SharpCompress sem o aplicativo ou a DLL do 7-Zip.",
        "• Extração opcional em unidade RAM já instalada, com verificações de memória e capacidade.",
        "• Exige mais de 12 GiB totais e pelo menos 5 GiB livres; o CHD permanece em disco.", "",
        "2.3.0 — 29/09/2026", "",
        "• Discos BIN com várias faixas e sem CUE podem ser reconstruídos quando o arranjo é identificável.",
        "• Corrigida a falsa detecção de links na antiga extração RAR de reserva.",
        "• A detecção automática distingue PS1 e PS2; o filtro pela plataforma escolhida continua disponível.",
        "• Interface em inglês e português brasileiro, ajuda de codificação mais clara e botão de restauração.",
        "• Registro de falhas e ação para relatar problemas.", "",
        "2.2.0 — 26/09/2026", "",
        "• As leituras de CPU e disco consideram o aplicativo e os conversores iniciados por ele.",
        "• CDs de PS2 com várias faixas são convertidos quando o arranjo é identificável.",
        "• Revisões diferentes do mesmo jogo recebem saídas separadas.",
        "• Parar agora cancela a tarefa e limpa os arquivos temporários.",
        "• A última pasta de entrada é lembrada; a saída padrão é otimizados.",
        "• Codecs podem ser marcados e as ferramentas têm uma página de configurações.",
        "• Suporte a capas de PS1.", "",
        "2.1.0 — 26/09/2026", "",
        "• Interface com cartões, opções avançadas recolhíveis e ajudas contextuais.",
        "• Nome, ícone e data de compilação do DiscForge CHD no aplicativo.",
        "• O painel do jogo se adapta a janelas estreitas.", "",
        "2.0.0 — 25/09/2026", "",
        "• Interface WinUI 3 com detalhes e capas no WebView2.",
        "• Extração SharpCompress com 7-Zip de reserva.",
        "• Pacote portátil com os componentes necessários.", "",
        "1.3.0 — 21/09/2026", "",
        "• Capas carregadas durante a identificação, com novas tentativas após falhas temporárias.",
        "• Cronômetro da entrada atual e indicadores de CPU e disco.",
        "• Quantidade de threads definida conforme o computador.", "",
        "1.2.0 — 20/09/2026", "",
        "• Imagens e arquivos de PS1/PS2 convertidos para CHD.",
        "• Opções de pasta, plataforma, codecs, hunk e threads.",
        "• Consulta por serial, nomes de jogos e capas de PS2.",
        "• Retomada ignora jogos convertidos; CHDs são verificados antes da remoção opcional do arquivo."
    });
}
